version: '3.8'

services:
  backend:
    build: ./backend
    image: salhihoussam/backend:latest
    container_name: flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    networks:
      - monitoring   # ✅ ajouté

  frontend:
    build: ./frontend
    image: salhihoussam/frontend:latest
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - monitoring   # ✅ ajouté

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
      - "5001:5001"
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped
    networks:
      - monitoring   # ✅ ajouté

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-temp:/opt/sonarqube/temp
    restart: unless-stopped
    networks:
      - monitoring   # ✅ ajouté

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      - monitoring   # ✅ ajouté

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring   # ✅ ajouté

volumes:
  nexus-data:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:
  sonarqube-temp:
  prometheus-data:
  grafana-data:

networks:
  monitoring:   # ✅ réseau défini
