version: '3.8'

services:
  backend:
    image: <NEXUS_IP>:5001/salhihoussam/backend:latest
    container_name: flask-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  frontend:
    image: <NEXUS_IP>:5001/salhihoussam/frontend:latest
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
      - "5001:5001"
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped

volumes:
  nexus-data:
