# Identifiant du projet
sonar.projectKey=pfa_project
sonar.projectName=PFA Flask React
sonar.projectVersion=1.0

# Répertoires sources
sonar.sources=backend,frontend/src

# Langues
sonar.language=py,js
sonar.sourceEncoding=UTF-8

# Python
sonar.python.version=3.11
sonar.tests=backend/tests
sonar.test.inclusions=**/test_*.py

# Exclusions
sonar.exclusions=frontend/node_modules/**,frontend/build/**
