sonar.projectKey=pfa
sonar.projectName=PFA-Project
sonar.projectVersion=1.0

# Code source à analyser
sonar.sources=backend,frontend/src

# Backend (Flask)
sonar.python.version=3.12

# Exclusions (backend + frontend + fichiers binaires)
sonar.exclusions=backend/venv/**,backend/**/__pycache__/**,frontend/node_modules/**,**/*.pyd,**/zoneinfo/**

# Encodage
sonar.sourceEncoding=UTF-8

# Frontend (React)
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# Rapport de test backend
sonar.python.coverage.reportPaths=backend/coverage.xml
