
pipeline {
    agent any

    stages {
        stage('Clone repository') {
            steps {
                git branch: 'stagepfa', url: 'https://github.com/SALHIHoussam/pfa.git'
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                python3 -m venv venv
                source venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
        }

        stage('Run tests') {
            steps {
                sh '''
                source venv/bin/activate
                pytest || echo "Pas de tests, on continue..."
                '''
            }
        }

        stage('Run Flask') {
            steps {
                sh '''
                source venv/bin/activate
                export FLASK_APP=app.py
                flask run --host=0.0.0.0 --port=5000
                '''
            }
        }
    }
}
